name       : haskell-echo
version    : 0.1.3
release    : 2
source     :
    - http://hackage.haskell.org/package/echo-0.1.3/echo-0.1.3.tar.gz : 704f07310f8272d170f8ab7fb2a2c13f15d8501ef8310801e36964c8eff485ef
license    : BSD-3-Clause
component  : programming.haskell
summary    : A cross-platform, cross-console way to handle echoing terminal input
description: |
    A cross-platform, cross-console way to handle echoing terminal input
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    sed -i "s|< 1.5|< 1.7|g" echo.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
