name       : haskell-echo
version    : 0.1.4
release    : 3
source     :
    - https://hackage.haskell.org/package/echo-0.1.4/echo-0.1.4.tar.gz : c9fe1bf2904825a65b667251ec644f197b71dc5c209d2d254be5de3d496b0e43
license    : BSD-3-Clause
component  : programming.haskell
summary    : A cross-platform, cross-console way to handle echoing terminal input
description: |
    A cross-platform, cross-console way to handle echoing terminal input
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
